---
title: "New Sensitivity Analysis Feb"
author: "Gustavo Reyes"
date: "2/1/2021"
output: html_document
---

# Sensitivity Analysis Student Prevalence
```{r}
# Analysis of Individual Fruit Items --------------------------------------

#1. Start from here
  #This section creates a data frame with every item, Including repeated items, since it is a snapshot of the end of every service
Individual_Analysis_Fr_Sens<-Individual_Analysis_Fr_CopOFF  
#Individual_Analysis_Fr<-bind_rows(List_Sens_Fr)

#2. find the dupplicates
  #this step filters replicated based on the ID
  Individual_Analysis_Fr_Sens<-Individual_Analysis_Fr_Sens %>% 
    group_by(ID) %>% 
    filter(TotServices==max(TotServices))

#3. Create a vector to explain if something were in the share table
  STYN_Vector<-c()
  for (i in 1:nrow(Individual_Analysis_Fr_Sens)){
    if (Individual_Analysis_Fr_Sens[i,colnames(Individual_Analysis_Fr_Sens)=="STtimes"]>0){
      STYN_Vector<-c(STYN_Vector,TRUE)
    }else if(Individual_Analysis_Fr_Sens[i,colnames(Individual_Analysis_Fr_Sens)=="STtimes"]==0){
      STYN_Vector<-c(STYN_Vector,FALSE)
    }
  }

  
#4. Number of touches

  Touches_Number<-lengths(regmatches(Individual_Analysis_Fr_Sens$History, gregexpr("Touched", Individual_Analysis_Fr_Sens$History)))
  
#5. Running Average Contamination of student that touches specific fruit. 
  
  ListTouches<-strsplit(Individual_Analysis_Fr_Sens$TouchesContHist,",")
  ListTouches<-lapply(ListTouches, function(x) x[x!="NA"])
  ListTouches<-lapply(ListTouches, function(x) as.numeric(x))
  TouchesContHist<-sapply(X = ListTouches, FUN = mean)
  Individual_Analysis_Fr_Sens$TouchesContHistAvr<-TouchesContHist
  sum(is.na(TouchesContHist))

#6. Creation of Dataframe for indvidual Analysis 

  Analysis_Individual<-data.frame(
    "InContamination"=Individual_Analysis_Fr_Sens$InContamination,
    "TouchesNo"=Touches_Number,
    "TouchesContHistAvr"=Individual_Analysis_Fr_Sens$TouchesContHistAvr,
    "STTimes"= Individual_Analysis_Fr_Sens$STtimes,
    "TotServices"=Individual_Analysis_Fr_Sens$TotServices,
    "Shared"=STYN_Vector,
    "DeltaCont"= (Individual_Analysis_Fr_Sens$Contamination-Individual_Analysis_Fr_Sens$InContamination),
    "Contamination" = Individual_Analysis_Fr_Sens$Contamination
  )
  
  #7.  Sensitivity Analysis of table

  Pcc2<-pcc(X=Analysis_Individual[,1:6], y=Analysis_Individual$Contamination,rank = TRUE, nboot = 100)
  Pcc2
  plot(Pcc2)

```
```{r}
#8 Visuals , remaing the columns to that no error in ggplot
  names(Pcc2$PRCC)=c("original", "bias" ,"std.error", "minci","maxci")

#Ggplot, here is similar to a tornado plot. Also there are error bars on the 95th percentile
  

  
  ggplot(data = Pcc2$PRCC, aes(x=rownames(Pcc2$PRCC),y=original ))+
    geom_bar(stat = "identity", position = "identity")+
    geom_errorbar(aes(ymin=minci, ymax=maxci), width=.1,col="blue")+
    ylab("Partial Correlation Coefficient")+
    xlab("Action")+
    ggtitle("Sensitivity Analysis Individual Items: Final Contamination PFU/Item")+
    scale_x_discrete(labels=c("Initial Contamination", "Shared", "Times in ST", "Total services","Overall Transfer From Touches", "Number of Touches")) +
    coord_flip()+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(text = element_text(size=13))
```

