---
title: "New Sens"
author: "Gustavo Reyes"
date: "2/2/2021"
output: html_document
---
#Main Ideas of the sens Analysis
The goals of this model is to create a sensitivity analysis that changes based on the inputs. 
The general output for the model will be the mean prevalence of ill students
The inputs of interest and their paths are the following
  1. Student Contamination: 
      - mass_feces_hands: rpert(1,-8,-3,-1,shape = 4) [Input_random]
        97.5th: -1.443
        Median: -3.382
        2.5th:  -6.179726
      - HU_NV_in_Feces : rpert(1,4,8,10,shape = 4) [Input_random]
        97.5th:  9.523563 
        Median:  7.747
        2.5th:   5.397141
      -LogRed: rpert(1,0.17,0.45,6,shape = 4) [Input_random]
        97.5th: 3.473241 
        Median: 1.1279
        2.5th:  0.2295374
      -Pr_WashingHand: .42 Static [Input_random]
      -Pr_Student_iC: 0.04 [Input_Static]
  2. Touching: 
      ntouched fruit: rnorm(round(rnorm(1,3,.5),0)) [Input_Random]
        97.5th: 4
        Median: 3
        2.5th:  2
      -Prevalence: Static 4% 
  3.Tranfer Probabilities: 
    -TrP_H_F<-inv.logit(rnorm(1,-3.86,Res_Trans)) [Input_Random]
        97.5th: 0.5012043
        Median: 0.0206298
        2.5th:  0.0004438392
    -TrP_F_H<-inv.logit(rnorm(1,-2.95,Res_Trans)) [Input_Random]
        97.5th: 0.7135126
        Median: 0.0497069
        2.5th:  0.001098976   
    -TrP_H_S<-inv.logit(rnorm(1,-3.82,Res_Trans)) [Input_Random]
        97.5th: 0.5107151
        Median: 0.0214587
        2.5th:  0.0004619996  
    -TrP_S_H<-inv.logit(rnorm(1,0.11,Res_Trans))[Input_Random]
        97.5th: 0.98147
        Median: 0.5277576
        2.5th:  0.02297
  4. Contamination of Fruit, Right now not in system but I will add here. 
    -Prevalence: rbetagen(1,0.79,1.03,0.0,0.2) [Input_Functions]
        97.5th: 0.1929986
        Median: 0.08123
        2.5th:  0.001825192
    - HuNoV_ContFruit: rlnormTrunc(1,2.38,3.52, 0,6.97)  [Input_Functions]
        97.5th: 6.304337 
        Median: 0.7583
        2.5th:  0.003518262
  5. Washing: Reduction of washing: [Input_Functions]
    - 2 log
  

#Starting. 
```{r}



```

