---
title: "Share Table Analysis with DR"
author: "Gustavo Reyes"
date: "1/11/2021"
output: html_document
---
Share Table Analysis


#1Run with Share Table on. 
```{r}
Func_Rep_DR<-function(DF_DR_Analysis){
  DF_DR_Analysis$Infection<-apply(DF_DR_Analysis,1,Func_DR_Infection)
  Number_Inf_Fr<-sum(DF_DR_Analysis$Infection==TRUE)
  #
  DF_DR_Analysis$Illness<-apply(DF_DR_Analysis,1,Func_DR_Illness)
  Number_Ill_Fr<-sum(DF_DR_Analysis$Illness==TRUE)
  l<-list("infection"=Number_Inf_Fr, "Illness"=Number_Ill_Fr )
  return(l)
}
```


```{r}
#Setting Working Directory
#setwd("C:/Users/gareyes3/Documents/GitHub/Share-Table-QMRA/R") 
setwd("G:/Share Table QMRA/Share-Table-QMRA/R")
```

```{r}
#Opening Libary and Inputs
source("Util_Library.R")
```

```{r}
#Inputs and Source Files
# Source Files ------------------------------------------------------------

#Inputs
source("Input_Static.R")
source("Input_Functions.R")
source("Util_DFFunctions.R")
source("Util_DFWeekCreation.R")
source("Util_Counter&Lists.R")
#Functions
source("Util_Functions.R")
source("Util_CCFunctions2.R")
source("Util_VisualFunctions.R")

```

```{r warning=TRUE}
#Running Loop First:
start_time<-Sys.time()
source("Main_Loops2.R")
```

```{r}
#Summary DFs for Future. 

#Creating Data Frame of Consumed Items for all the products

  #Fruit

#1. Start from here
Individual_Analysis_Fr<-bind_rows(List_Sens_Fr)
Individual_Analysis_Fr_CopON<-bind_rows(List_Sens_Fr)

#Adding Type Column
Individual_Analysis_Fr$Type<-"Fruit"

#2. find the dupplicates
#this step filters replicated based on the ID
Individual_Analysis_Fr<-Individual_Analysis_Fr %>% 
  group_by(ID) %>% 
  filter(TotServices==max(TotServices))%>%
  filter(Location=="Consumed")%>%
  select(ID,Type,ConsumedBy,Contamination, ContConsumed, Infection,Illness,week)
#3
ST_ON_Analysis<-Individual_Analysis_Fr

```


#Running Model Now With ST Off

```{r}
#Inputs and Source Files
# Source Files ------------------------------------------------------------


#Inputs
source("Input_Static.R")
source("Input_Functions.R")
source("Util_DFFunctions.R")
source("Util_DFWeekCreation.R")
source("Util_Counter&Lists.R")
#Functions
source("Util_Functions.R")
source("Util_CCFunctions2.R")
source("Util_VisualFunctions.R")

#Share Table Toggle 
  
  #Include Share Table:
  Share_Table_YN<-0
  #NOTE: Turn off Re-Sharing and -ST to reservice too (next section)

# Re-Sharing, Re-Service 

  #Share Table to Service line after every Day # note turn in 1 if ST on
  STtoReservice_YN<-0
  #Re-Sharing of Share table items after every service # note turn in 1 is ST on
  Resharing_YN<-0

```

```{r warning=TRUE}
#Running Loop First:
start_time<-Sys.time()
source("Main_Loops2.R")
```

```{r}
#Summary DFs for Future. 

#Creating Data Frame of Consumed Items for all the products

  #Fruit

#1. Start from here
Individual_Analysis_Fr<-bind_rows(List_Sens_Fr)
Individual_Analysis_Fr_CopOFF<-bind_rows(List_Sens_Fr)

#Adding Type Column
Individual_Analysis_Fr$Type<-"Fruit"

#2. find the dupplicates
#this step filters replicated based on the ID
Individual_Analysis_Fr<-Individual_Analysis_Fr %>% 
  group_by(ID) %>% 
  filter(TotServices==max(TotServices))%>%
  filter(Location=="Consumed")%>%
  select(ID,Type,ConsumedBy,Contamination, ContConsumed, Infection,Illness,week)
#3
ST_OFF_Analysis<-Individual_Analysis_Fr

```

#Dose Response Model
#ST ON

```{r}
#ST ON
ST_ON_Analysis_Copy<-ST_ON_Analysis


df1<-ST_ON_Analysis_Copy %>% 
  group_by(week) %>% 
  summarize(count=n())
df1$week<-paste("Week",df1$week)



 ST_ON_Analysis<-ST_ON_Analysis%>%
      group_by(ConsumedBy)%>%
      summarise(Contamination = sum(Contamination))

    ST_ON_Analysis$week <- substr(ST_ON_Analysis$ConsumedBy, 1, 3) 
    ST_ON_Analysis$Infection<-as.logical("")
    ST_ON_Analysis$Illness<-as.logical("")
    
#Analysis For weekly Dose Response ON

Reps_DR<-100

List_week_DR<-split(x=ST_ON_Analysis,f=ST_ON_Analysis$week)
lista<-replicate(Reps_DR,lapply(List_week_DR,Func_Rep_DR),simplify = FALSE)
list_Df_Rep<-lapply(lista, Func_List2DF)
list_Df_Rep<-lapply(list_Df_Rep, setNames, c("Infections", "Illness"))
list_Df_Rep<-lapply(list_Df_Rep,bind_rows)
list_Df_Rep<-bind_cols(list_Df_Rep)


df_inf_Week_ON = list_Df_Rep[,seq(1, ncol(list_Df_Rep), 2) ]
df_ill_Week_ON = list_Df_Rep[,seq(2, ncol(list_Df_Rep), 2) ]

df_inf_Week_ON<-as.data.frame(t(df_inf_Week_ON))
df_ill_Week_ON<-as.data.frame(t(df_ill_Week_ON))

rownames(df_inf_Week_ON)<-paste("Rep",1:Reps_DR)
rownames(df_ill_Week_ON)<-paste("Rep",1:Reps_DR)
colnames(df_inf_Week_ON)<-paste("Week",1:Sens_Iterations)
colnames(df_ill_Week_ON)<-paste("Week",1:Sens_Iterations)    

```


#Dose Response Model
#ST Off

```{r}
#ST OFF
ST_OFF_Analysis_Copy<-ST_OFF_Analysis

 ST_OFF_Analysis<-ST_OFF_Analysis%>%
      group_by(ConsumedBy)%>%
      summarise(Contamination = sum(Contamination))

    ST_OFF_Analysis$week <- substr(ST_OFF_Analysis$ConsumedBy, 1, 3)
    ST_OFF_Analysis$Infection<-as.logical("")
    ST_OFF_Analysis$Illness<-as.logical("")
    
#Analysis For weekly Dose Response ON

Reps_DR<-100

List_week_DR<-split(x=ST_OFF_Analysis,f=ST_OFF_Analysis$week)
lista<-replicate(Reps_DR,lapply(List_week_DR,Func_Rep_DR),simplify = FALSE)
list_Df_Rep<-lapply(lista, Func_List2DF)
list_Df_Rep<-lapply(list_Df_Rep, setNames, c("Infections", "Illness"))
list_Df_Rep<-lapply(list_Df_Rep,bind_rows)
list_Df_Rep<-bind_cols(list_Df_Rep)


df_inf_Week_OFF = list_Df_Rep[,seq(1, ncol(list_Df_Rep), 2) ]
df_ill_Week_OFF = list_Df_Rep[,seq(2, ncol(list_Df_Rep), 2) ]

df_inf_Week_OFF<-as.data.frame(t(df_inf_Week_OFF))
df_ill_Week_OFF<-as.data.frame(t(df_ill_Week_OFF))

rownames(df_inf_Week_OFF)<-paste("Rep",1:Reps_DR)
rownames(df_ill_Week_OFF)<-paste("Rep",1:Reps_DR)
colnames(df_inf_Week_OFF)<-paste("Week",1:Sens_Iterations)
colnames(df_ill_Week_OFF)<-paste("Week",1:Sens_Iterations) 


```

```{r}
df_inf_Week_ON_Box <- melt(df_inf_Week_ON, measure.var = paste("Week",1:Sens_Iterations))

df_inf_Week_ON_Box_Prev<-merge(df_inf_Week_ON_Box, df1, by.x='variable', by.y='week')
df_inf_Week_ON_Box_Prev$Prev<-df_inf_Week_ON_Box_Prev$value/df_inf_Week_ON_Box_Prev$count

ggplot(df_inf_Week_ON_Box_Prev, aes(x = variable, y = Prev)) + 
  geom_boxplot() + 
  theme_bw()+
  ylab("# Infected Student")+
  xlab("Week #") +
  ggtitle("ST ON: Dose Response 100 replicates, Prevalence of Infected Students by week")+ 
  theme(plot.title = element_text(hjust = 0.5))

df_ill_Week_ON_Box <- melt(df_ill_Week_ON, measure.var = paste("Week",1:Sens_Iterations))
df_ill_Week_ON_Box_Prev<-merge(df_ill_Week_ON_Box, df1, by.x='variable', by.y='week')
df_ill_Week_ON_Box_Prev$Prev<-df_ill_Week_ON_Box_Prev$value/df_ill_Week_ON_Box_Prev$count

ggplot(df_ill_Week_ON_Box_Prev, aes(x = variable, y = Prev)) + 
  geom_boxplot() + 
  theme_bw()+
  ylab("Prevalence of Ill Students")+
  xlab("Week #")+
  ggtitle("ST ON: Dose Response 100 replicates, Prevalence of Ill Students by week")+ 
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}



df_inf_Week_OFF_Box <- melt(df_inf_Week_OFF, measure.var = paste("Week",1:Sens_Iterations))

df_inf_Week_OFF_Box_Prev<-merge(df_inf_Week_OFF_Box, df1, by.x='variable', by.y='week')
df_inf_Week_OFF_Box_Prev$Prev<-df_inf_Week_OFF_Box_Prev$value/df_inf_Week_OFF_Box_Prev$count

ggplot(df_inf_Week_OFF_Box_Prev, aes(x = variable, y = Prev)) + 
  geom_boxplot() + 
  theme_bw()+
  ylab("# Infected Student")+
  xlab("Week #") +
  ggtitle("Weekly Dose Response Distribution 100 replicates Infected Students")+ 
  theme(plot.title = element_text(hjust = 0.5))

df_ill_Week_OFF_Box <- melt(df_ill_Week_OFF, measure.var = paste("Week",1:Sens_Iterations))

df_ill_Week_OFF_Box_Prev<-merge(df_ill_Week_OFF_Box, df1, by.x='variable', by.y='week')
df_ill_Week_OFF_Box_Prev$Prev<-df_ill_Week_OFF_Box_Prev$value/df_ill_Week_OFF_Box_Prev$count

ggplot(df_ill_Week_OFF_Box_Prev, aes(x = variable, y = Prev)) + 
  geom_boxplot() + 
  theme_bw()+
  ylab("# Ill Student")+
  xlab("Week #")+
  ggtitle("Weekly Dose Response Distribution, 100 replicates: Ill Students")+ 
  theme(plot.title = element_text(hjust = 0.5))
```
#Boxplot Together
```{r}
#Infected
df_inf_Week_ON_Box_Prev$Int<-"on"
df_inf_Week_OFF_Box_Prev$Int<-"off"

df_inf_Week_Tog_Box<-bind_rows(df_inf_Week_ON_Box_Prev,df_inf_Week_OFF_Box_Prev)

ggplot(df_inf_Week_Tog_Box, aes(x = variable, y = Prev, fill=Int)) + 
  geom_boxplot() + 
  theme_bw()+
  ylab("Prevalence of Infected Student")+
  xlab("Week #") +
  ggtitle("ST Status: Compaison Weekly Dose Response Distribution: Prevalence Infected Students")+ 
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "ST Status")

#Ill

df_ill_Week_ON_Box_Prev$Int<-"on"
df_ill_Week_OFF_Box_Prev$Int<-"off"

df_ill_Week_Tog_Box<-bind_rows(df_ill_Week_ON_Box_Prev,df_ill_Week_OFF_Box_Prev)

Ill_Prev_Comb<-ggplot(df_ill_Week_Tog_Box, aes(x = variable, y = Prev, fill=Int)) + 
  geom_boxplot() + 
  theme_bw()+
  ylab("Prevalence of Ill Students")+
  xlab("Week #") +
  ggtitle("ST Status: Compaison Weekly Dose Response Distribution: Prevalence Ill Students")+ 
  theme(plot.title = element_text(hjust = 0.5))+
  labs(fill = "ST Status")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave(filename = "Ill_Prev_Comb.png", path = "Dose Response",width = 40,height = 10,)
print(Ill_Prev_Comb)

```

#Ribon Together
```{r}

Ribon_Ill_OFF<-df_ill_Week_OFF_Box_Prev%>%
  group_by(variable)%>%
  summarise(PrevMed= median(Prev),Prev975= quantile(Prev,.975),Prev025= quantile(Prev,.025))%>%
  mutate(Type = "Off")

df_ill_Week_ON_Box_Prev<-df_ill_Week_ON_Box_Prev[,-2]

Ribon_Ill_ON<-df_ill_Week_ON_Box_Prev%>%
  group_by(variable)%>%
  summarise(PrevMed= median(Prev),Prev975= quantile(Prev,.975),Prev025= quantile(Prev,.025))%>%
  mutate(Type = "on")

Ribbon_Ill_DF<-bind_rows(Ribon_Ill_OFF,Ribon_Ill_ON)

Ribbon_Ill<-ggplot(Ribbon_Ill_DF, aes(x = variable, y = PrevMed, group = Type)) + 
  geom_ribbon(aes(ymin = Prev975, ymax = Prev025, fill=Type), alpha=0.3 )+ 
  geom_point(aes(color = Type))+
  geom_line(aes(color = Type), size = .5) +   
  labs(x = "Week #", y = "Prevalence of Ill Student per Week") +
  scale_fill_manual(name = '2.5th-97.5th Percentile', values = c("dodgerblue1", "tomato4", "seagreen1"))+ 
  scale_color_manual(name = 'Median', values = c("dodgerblue1", "tomato4", "seagreen1"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave(filename = "Ribbon_Ill.png", path = "Dose Response",width = 20,height = 7,)

print(Ribbon_Ill)
```



#Comparison of amounts consumed. 
```{r}
ST_OFF_Analysis_Con<-Individual_Analysis_Fr_CopOFF
ST_ON_Analysis_Con<-Individual_Analysis_Fr_CopON

ST_OFF_Analysis_Con$Type<-"off"
ST_ON_Analysis_Con$Type<-"on"

ST_Comb_Analysis_Con<-bind_rows(ST_OFF_Analysis_Con,ST_ON_Analysis_Con)

ggplot(data =ST_Comb_Analysis_Con, aes(x = Type,fill=Location)  )+
  geom_bar()+
  geom_text(stat = "count",aes(label=..count..),position = position_stack(vjust = .5))

```


#Plots Creation for Exposure
```{r}
#Histogram Exposure
ST_ON_Analysis_Log<-ST_ON_Analysis
ST_ON_Analysis_Log$Contamination[ST_ON_Analysis_Log$Contamination==0]<-(.99)
ST_ON_Analysis_Log$Log<-log10(ST_ON_Analysis_Log$Contamination)
ST_ON_Analysis_Log$Category<-""
ST_ON_Analysis_Log$OnOff<-"ON"

ST_OFF_Analysis_Log<-ST_OFF_Analysis
ST_OFF_Analysis_Log$Contamination[ST_OFF_Analysis_Log$Contamination==0]<-(.99)
ST_OFF_Analysis_Log$Log<-log10(ST_OFF_Analysis_Log$Contamination)
ST_OFF_Analysis_Log$Category<-""
ST_OFF_Analysis_Log$OnOff<-"OFF"


ST_ON_Analysis$OnOff<-"ON"
ST_OFF_Analysis$OnOff<-"OFF"
ST_Comb_Analysis_Log<-bind_rows(ST_ON_Analysis_Log,ST_OFF_Analysis_Log)
ST_Comb_Analysis<-bind_rows(ST_ON_Analysis,ST_OFF_Analysis)


Wrapped_Histograms<-ggplot(data = ST_Comb_Analysis_Log,aes(x=Log))+
  geom_histogram(colour="black", alpha=.2,bins =15,boundary = -.001)+
  facet_wrap(~ OnOff)+
  scale_x_continuous( )+
  xlab("Contamination log GEC/Item")+
  ylab("Number of Students")+
  ggtitle("Share Tables ON: Contamination distribution Consumed by Students")+ 
  theme(plot.title = element_text(hjust = 0.5))+
  stat_bin(aes(y=..count.., label=..count..), geom="text", vjust=-.2,bins=15, boundary = -.001,size=3)

ggsave(filename = "Wrapped_Histograms.png", path = "Dose Response",width = 10,height = 6,)
print(Wrapped_Histograms)

ST_Comb_Analysis$Contamination<-log10(ST_Comb_Analysis$Contamination)
ggplot(data = ST_Comb_Analysis)+
  geom_boxplot(mapping = aes(x=OnOff, y =Contamination, fill =OnOff),varwidth = TRUE)

```

```{r}


for (i in 1:nrow(ST_ON_Analysis_Log)){
  Conta<-as.numeric(ST_ON_Analysis_Log$Contamination[i])
  if(Conta == .99 ){
    ST_ON_Analysis_Log$Category[i] <-"0"
  } else if(Conta >0 && Conta< 100 ){
    ST_ON_Analysis_Log$Category[i]  <-"<0 - 99"
  }else if(Conta >= 100 && Conta < 1000 ){
    ST_ON_Analysis_Log$Category[i]  <-"100 - 999"
  }else if(Conta >=1000 ){
    ST_ON_Analysis_Log$Category[i]  <-">=1000"
  }
}


PlotOrder<-c("0","<0 - 99","100 - 999",">=1000")

ST_ON_Analysis_Log %>% 
  count(Category) %>% 
  mutate(perc = n / nrow(ST_ON_Analysis_Log)) %>%
  slice(match(Category,PlotOrder))-> tips2

tips2$OnOff<-"ON"

#off

for (i in 1:nrow(ST_OFF_Analysis_Log)){
  Conta<-as.numeric(ST_OFF_Analysis_Log$Contamination[i])
  if(Conta == .99 ){
    ST_OFF_Analysis_Log$Category[i] <-"0"
  } else if(Conta >0 && Conta< 100 ){
    ST_OFF_Analysis_Log$Category[i]  <-"<0 - 99"
  }else if(Conta >= 100 && Conta < 1000 ){
    ST_OFF_Analysis_Log$Category[i]  <-"100 - 999"
  }else if(Conta >=1000 ){
    ST_OFF_Analysis_Log$Category[i]  <-">=1000"
  }
}


PlotOrder<-c("0","<0 - 99","100 - 999",">=1000")

ST_OFF_Analysis_Log %>% 
  count(Category) %>% 
  mutate(perc = n / nrow(ST_OFF_Analysis_Log)) %>%
  slice(match(Category,PlotOrder))-> tips3

tips3$OnOff<-"OFF"

tips4<-bind_rows(tips2,tips3)

ggplot(data =tips4, aes(x = OnOff,y=perc, fill=factor(Category, levels=c("0","<0 - 99","100 - 999",">=1000"))))+
  geom_col(width = .2)+
  geom_text_repel(aes(x = OnOff, 
                      y = perc, 
                      label = paste(round(perc*100,2),"%")),nudge_y = -.2, nudge_x = .15, direction = "x")+
  geom_text_repel(aes(x = OnOff, 
                      y = perc, 
                      label = n),nudge_x = -.15,nudge_y = -.2, direction = "x")+
  labs(fill = "Category")+
  scale_x_discrete(expand = c(.5, 0))+
  coord_flip()+
  xlab(label = "Share Table Status")+
  ylab(label = "")+
    ggtitle("Composition on Exposure of Individual Students (%)")+ 
  theme(plot.title = element_text(hjust = 0.5))

```

#Summary Table
```{r}
N_Student_ContSTON<-nrow(ST_ON_Analysis)
N_Student_ContSTOFF<-nrow(ST_OFF_Analysis)


MeanPRevON<-mean(df_ill_Week_ON_Box_Prev$Prev)
PRev975ON<-quantile(df_ill_Week_ON_Box_Prev$Prev,.975)
PRev025ON<-quantile(df_ill_Week_ON_Box_Prev$Prev,.025)

MeanPRevOFF<-mean(df_ill_Week_OFF_Box_Prev$Prev)
PRev975OFF<-quantile(df_ill_Week_OFF_Box_Prev$Prev,.975)
PRev025OFF<-quantile(df_ill_Week_OFF_Box_Prev$Prev,.025)

MeanPRevinfON<-mean(df_inf_Week_ON_Box_Prev$Prev)
PRev975infON<-quantile(df_inf_Week_ON_Box_Prev$Prev,.975)
PRev025infON<-quantile(df_inf_Week_ON_Box_Prev$Prev,.025)

MeanPRevinfOFF<-mean(df_inf_Week_OFF_Box_Prev$Prev)
PRev975infOFF<-quantile(df_inf_Week_OFF_Box_Prev$Prev,.975)
PRev025infOFF<-quantile(df_inf_Week_OFF_Box_Prev$Prev,.025)



Summary_Comparison<-data.frame(
  "Treatment" = c(1:2),
  "Treatment Desc" = c("Baseline:ST ON", "Baseline: Share Tables OFF"),
  "NWeeks" = Sens_Iterations,
  "Participating Students" = N_Iterations*Service_No* Food_Days*Sens_Iterations,
  "NStudentCosumedFood" = c(N_Student_ContSTON,N_Student_ContSTOFF),
  "Prevalence Consump" = (Summary_Comparison$NStudentCosumedFood /Summary_Comparison$Participating.Students),
  "0" = c(tips2$perc[4],0)*100 ,
  ">0" = c(tips2$perc[3],0)*100,
  ">100"=c(tips2$perc[2],0)*100,
  ">1000"= c(tips2$perc[1],0)*100,
    "Mean Prevalence Inf" = c(MeanPRevinfON,MeanPRevinfOFF)*100,
  "Top 97.5 Inf"=c(PRev975infON,PRev975infOFF)*100,
  "Bot 025 Inf"=c(PRev025infON,PRev025infOFF)*100,
  "Mean Prevalence Ill" = c(MeanPRevON,MeanPRevOFF)*100,
  "Top 97.5 Ill"=c(PRev975ON,PRev975OFF)*100,
  "Bot 025 Ill"=c(PRev025ON,PRev025OFF)*100,
  stringsAsFactors = FALSE
  )






give.n <- function(x){
 return(c(y = median(x)*1.05, label = length(x))) 
# experiment with the multiplier to find the perfect position
}


# plot
ggplot(mtcars, aes(factor(cyl), mpg, label=rownames(mtcars))) +
 geom_boxplot(fill = "grey80", colour = "#3366FF") +
 stat_summary(fun.data = give.n, geom = "text", fun.y = median) 



ggplot(data = df_ill_Week_Tog_Box, aes(x= Int , y = Prev))+
  geom_boxplot() 


```


