---
title: "Summary_Plots_All"
author: "Gustavo Reyes"
date: "12/10/2020"
output: html_document
---

Here we organize the Data and Divide it into sections. 
```{r}
#Creating Data Frame of Consumed Items for all the products

  #Fruit

#1. Start from here
Individual_Analysis_Fr<-bind_rows(List_Sens_Fr)

#Adding Type Column
Individual_Analysis_Fr$Type<-"Fruit"

#2. find the dupplicates
#this step filters replicated based on the ID
Individual_Analysis_Fr<-Individual_Analysis_Fr %>% 
  group_by(ID) %>% 
  filter(TotServices==max(TotServices))%>%
  filter(Location=="Consumed")%>%
  select(ID,Type,ConsumedBy,Contamination, ContConsumed, Infection,Illness,week)


  #PSS

#1. Start from here
Individual_Analysis_Pss<-bind_rows(List_Sens_Pss)

#Adding Type Column
Individual_Analysis_Pss$Type<-"Pss"

#2. find the dupplicates
#this step filters replicated based on the ID
Individual_Analysis_Pss<-Individual_Analysis_Pss %>% 
  group_by(ID) %>% 
  filter(TotServices==max(TotServices))%>%
  filter(Location=="Consumed")%>%
  select(ID,Type,ConsumedBy,Contamination, ContConsumed, Infection,Illness,week)


  #Pre 

#1. Start from here
Individual_Analysis_Pre<-bind_rows(List_Sens_Pre)

#Adding Type 
Individual_Analysis_Pre$Type<-"Pre"

#2. find the dupplicates
#this step filters replicated based on the ID
Individual_Analysis_Pre<-Individual_Analysis_Pre %>% 
  group_by(ID) %>% 
  filter(TotServices==max(TotServices))%>%
  filter(Location=="Consumed")%>%
  select(ID,Type,ConsumedBy,Contamination, ContConsumed, Infection,Illness,week)




```

```{r}
#Creating one data frame with the columns of interest to sort them ouy by student

DF_DR_Analysis<-bind_rows(Individual_Analysis_Fr,Individual_Analysis_Pss, Individual_Analysis_Pre)%>%
  group_by(ConsumedBy)%>%
  summarise(Contamination = sum(Contamination))

DF_DR_Analysis$week <- substr(DF_DR_Analysis$ConsumedBy, 1, 1)
DF_DR_Analysis$Infection<-as.logical("")
DF_DR_Analysis$Illness<-as.logical("")


```


```{r}

#Dose Response. Adding the Dose Response to the Items
Func_Rep_DR<-function(DF_DR_Analysis){
  DF_DR_Analysis$Infection<-apply(DF_DR_Analysis,1,Func_DR_Infection)
  Number_Inf_Fr<-sum(DF_DR_Analysis$Infection==TRUE)
  #
  DF_DR_Analysis$Illness<-apply(DF_DR_Analysis,1,Func_DR_Illness)
  Number_Ill_Fr<-sum(DF_DR_Analysis$Illness==TRUE)
  l<-list("infection"=Number_Inf_Fr, "Illness"=Number_Ill_Fr )
  return(l)
}

#Function to extract list into a Data Frame
Func_List2DF<-function(list){
  df<-data.frame(matrix(unlist(list), nrow=length(list), byrow=T),stringsAsFactors=FALSE)
  return(df)
}

lista<-replicate(5,Func_Rep_DR(DF_DR_Analysis),simplify = FALSE )

DF_DR_Rep<-Func_List2DF(lista)


```

```{r}
#Analysis For weekly Dose Response

Reps_DR<-100

List_week_DR<-split(x=DF_DR_Analysis,f=DF_DR_Analysis$week)
lista<-replicate(Reps_DR,lapply(List_week_DR,Func_Rep_DR),simplify = FALSE)
list_Df_Rep<-lapply(lista, Func_List2DF)
list_Df_Rep<-lapply(list_Df_Rep, setNames, c("Infections", "Illness"))
list_Df_Rep<-lapply(list_Df_Rep,bind_rows)
list_Df_Rep<-bind_cols(list_Df_Rep)


df_inf_Week = list_Df_Rep[,seq(1, ncol(list_Df_Rep), 2) ]
df_ill_Week = list_Df_Rep[,seq(2, ncol(list_Df_Rep), 2) ]

df_inf_Week<-as.data.frame(t(df_inf_Week))
df_ill_Week<-as.data.frame(t(df_ill_Week))

rownames(df_inf_Week)<-paste("Rep",1:Reps_DR)
rownames(df_ill_Week)<-paste("Rep",1:Reps_DR)
colnames(df_inf_Week)<-paste("Week",1:Sens_Iterations)
colnames(df_ill_Week)<-paste("Week",1:Sens_Iterations)


Summary_list_Df_Rep<-as.data.frame(list_Df_Rep,)
Summary_list_Df_Rep<-lapply(X=Summary_list_Df_Rep, mean)
Summary_list_Df_Rep<-as.data.frame(Summary_list_Df_Rep)
aaaaa<-split(Summary_list_Df_Rep, rep(1:ncol(Summary_list_Df_Rep), each= 2))
aaaaa<-bind_cols(aaaaa)
                                

```

