---
title: "Validation of Dose Response"
author: "Gustavo Reyes"
date: "12/10/2020"
output: html_document
---

```{r}
#Validation on the Infection
DF_Validation_DR<-data.frame(
  "Dose"=1:100000,
  "Pinf"="",
  stringsAsFactors = FALSE
)

for(i in 1:nrow(DF_Validation_DR)){
  alpha<-0.04
  betar<-0.055
  hunov<-as.numeric(DF_Validation_DR[i,colnames(DF_Validation_DR)== "Dose"])
  Probinf<-1-hyperg_1F1(a = alpha,b = alpha+betar,x = -hunov)
  DF_Validation_DR[i,colnames(DF_Validation_DR)== "Pinf"]<-Probinf
}

plot(DF_Validation_DR$Dose,DF_Validation_DR$Pinf)

```
```{r}
#Validation of theillness dose Response
DF_Validation_DR<-data.frame(
  "Dose"=c(10^1,10^1.5,10^2,10^2.5,10^3,10^3.5,10^4,10^4.5,10^5,10^5.5,10^6,10^6.5,10^7,10^7.5,10^8),
  "Pill"="",
  stringsAsFactors = FALSE
)

for(i in 1:nrow(DF_Validation_DR)){
  alpha<-0.04
  betar<-0.055
  hunov<-as.numeric(DF_Validation_DR[i,colnames(DF_Validation_DR)== "Dose"])
  Probill<-1-(1+nw*hunov)^(-r)
  DF_Validation_DR[i,colnames(DF_Validation_DR)== "Pill"]<-Probill
}

ggplot(data=DF_Validation_DR, aes(x=Dose,y=Pill))+
  geom_point()
```

